language: cpp
sudo: required
dist: xenial
env:
- BUILD_CONFIG=debug
- BUILD_CONFIG=release
- BUILD_CONFIG=debugdll
- BUILD_CONFIG=releasedll
matrix:
  include:
  - os: linux
    compiler: gcc
  - os: osx
    osximage: xcode10.2
  - os: osx
    osximage: xcode10.1
  - os: osx
    osximage: xcode10
  - os: osx
    osximage: xcode9.4
  - os: osx
    osximage: xcode9.3
  - os: osx
    osximage: xcode9.2
  - os: osx
    osximage: xcode9.1
  - os: osx
    osximage: xcode9
  - os: osx
    osximage: xcode8.3
  - os: osx
    osximage: xcode8
  - os: osx
    osximage: xcode7.3
  - os: osx
    osximage: xcode6.4
addons:
  apt:
    update: true
    packages:
    - p7zip-full 
    - libevent-dev 
    - libfreetype6-dev 
    - libirrlicht-dev 
    - liblua5.3-dev 
    - libsqlite3-dev 
    - libgl1-mesa-dev 
    - libglu-dev 
    - libgit2-dev
  homebrew:
    packages:
    - dylibbundler
    - p7zip
    - libevent
    - fmt
    - freetype
    - irrlicht
    - lua
    - sqlite 
    - curl
    - libgit2
    - nlohmann-json
before_install: if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then ./build-support/install-ubuntu-src.sh; fi
install: 
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then ./build-support/install-ubuntu-bin.sh; fi
- if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then ./build-support/install-macOS-bin.sh; fi
script:
- ./premake5 gmake2
- make -Cbuild clean
- make -Cbuild config=$BUILD_CONFIG
before_deploy: 
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then ./build-support/deploy-ubuntu.sh; fi
- if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then ./build-support/deploy-macOS.sh; fi
