language: cpp
sudo: required
dist: bionic
git:
  depth: 1
env:
  global:
  - BUILD_CONFIG=release
  - DEPLOY_BRANCH=travis-$TRAVIS_OS_NAME
  - MSBUILD_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
addons:
  apt:
    update: true
    packages:
    - p7zip-full 
    - libfreetype6-dev
    - libirrlicht-dev 
    - libgl1-mesa-dev 
    - libglu-dev 
  homebrew:
    update: true
    packages:
    - dylibbundler
    - gpatch
    - p7zip
    - lua
    - libevent
    - freetype
    - sqlite
    - curl
    - libgit2
    - fmt
    - nlohmann-json
matrix:
  include:
  - name: "Windows 10"
    os: windows
    env:
    - VCPKG_ROOT=/c/vcpkg
    - VCPKG_DEFAULT_TRIPLET=x86-windows-static
    - VCPKG_LIBS="libevent lua[cpp] sqlite3 fmt curl libgit2 nlohmann-json bzip2 libjpeg-turbo libpng zlib"
    - VCPKG_CACHE_ZIP_URL=https://github.com/kevinlul/edopro-vcpkg-cache/raw/master/installed.zip
    - DXSDK_DIR=/c/d3d9sdk/
    - DEPLOY_DIR=deploy
  - name: "Bionic GCC7"
    os: linux
    compiler: gcc  
    env:
    - VCPKG_ROOT=./vcpkg
    - VCPKG_LIBS="lua libevent sqlite3 fmt nlohmann-json curl libgit2"
    - VCPKG_CACHE_ZIP_URL=https://github.com/kevinlul/edopro-vcpkg-cache/raw/master/installed-linux.7z
  - name: "Mojave"
    os: osx
    osx_image: xcode10.3
    env: 
    - MACOSX_DEPLOYMENT_TARGET=10.11
    - SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk"
    cache:
      directories:
      - cache
before_install: ./travis/install-premake5.sh
install: ./travis/dependencies.sh
script: ./travis/build.sh
before_deploy: ./travis/predeploy.sh
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./ocgcore/travis/deploy-windows.sh
  on:
    condition: "$TRAVIS_OS_NAME == windows"
- provider: pages
  skip_cleanup: true
  local_dir: deploy
  github_token: $DEPLOY_TOKEN
  repo: $DEPLOY_REPO
  target_branch: $DEPLOY_BRANCH
  on:
    condition: "$TRAVIS_OS_NAME != windows"
before_cache:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    mkdir -p cache &&
    cp -r /usr/local/include/irrlicht cache/irrlicht &&
    cp /usr/local/lib/libIrrlicht.a cache/libIrrlicht.a &&
    cp -r /usr/local/Cellar/libevent/2.1.11 cache/libevent;
  fi
