irrlicht_inc = [include_directories('./include')]

irrlicht_sources = [
	'src/aesGladman/aescrypt.cpp',
	'src/aesGladman/aeskey.cpp',
	'src/aesGladman/aestab.cpp',
	'src/aesGladman/fileenc.cpp',
	'src/aesGladman/hmac.cpp',
	'src/aesGladman/prng.cpp',
	'src/aesGladman/pwd2key.cpp',
	'src/aesGladman/sha1.cpp',
	'src/aesGladman/sha2.cpp',
	'src/lzma/LzmaDec.c',
	'src/C3DSMeshFileLoader.cpp',
	'src/CAnimatedMeshHalfLife.cpp',
	'src/CAnimatedMeshMD2.cpp',
	'src/CAnimatedMeshMD3.cpp',
	'src/CAnimatedMeshSceneNode.cpp',
	'src/CAttributes.cpp',
	'src/CB3DMeshFileLoader.cpp',
	'src/CB3DMeshWriter.cpp',
	'src/CBSPMeshFileLoader.cpp',
	'src/CBillboardSceneNode.cpp',
	'src/CBoneSceneNode.cpp',
	'src/CBurningShader_Raster_Reference.cpp',
	'src/CCSMLoader.cpp',
	'src/CCameraSceneNode.cpp',
	'src/CColladaFileLoader.cpp',
	'src/CColladaMeshWriter.cpp',
	'src/CColorConverter.cpp',
	'src/CCubeSceneNode.cpp',
	'src/CD3D9Driver.cpp',
	'src/CD3D9HLSLMaterialRenderer.cpp',
	'src/CD3D9NormalMapRenderer.cpp',
	'src/CD3D9ParallaxMapRenderer.cpp',
	'src/CD3D9RenderTarget.cpp',
	'src/CD3D9ShaderMaterialRenderer.cpp',
	'src/CD3D9Texture.cpp',
	'src/CDMFLoader.cpp',
	'src/CDefaultGUIElementFactory.cpp',
	'src/CDefaultSceneNodeAnimatorFactory.cpp',
	'src/CDefaultSceneNodeFactory.cpp',
	'src/CDepthBuffer.cpp',
	'src/CDummyTransformationSceneNode.cpp',
	'src/CEGLManager.cpp',
	'src/CEmptySceneNode.cpp',
	'src/CFPSCounter.cpp',
	'src/CFileList.cpp',
	'src/CFileSystem.cpp',
	'src/CGLXManager.cpp',
	'src/CGUIButton.cpp',
	'src/CGUICheckBox.cpp',
	'src/CGUIColorSelectDialog.cpp',
	'src/CGUIComboBox.cpp',
	'src/CGUIContextMenu.cpp',
	'src/CGUIEditBox.cpp',
	'src/CGUIEnvironment.cpp',
	'src/CGUIFileOpenDialog.cpp',
	'src/CGUIFont.cpp',
	'src/CGUIImage.cpp',
	'src/CGUIImageList.cpp',
	'src/CGUIInOutFader.cpp',
	'src/CGUIListBox.cpp',
	'src/CGUIMenu.cpp',
	'src/CGUIMeshViewer.cpp',
	'src/CGUIMessageBox.cpp',
	'src/CGUIModalScreen.cpp',
	'src/CGUIProfiler.cpp',
	'src/CGUIScrollBar.cpp',
	'src/CGUISkin.cpp',
	'src/CGUISpinBox.cpp',
	'src/CGUISpriteBank.cpp',
	'src/CGUIStaticText.cpp',
	'src/CGUITabControl.cpp',
	'src/CGUITable.cpp',
	'src/CGUIToolBar.cpp',
	'src/CGUITreeView.cpp',
	'src/CGUIWindow.cpp',
	'src/CGeometryCreator.cpp',
	'src/CImage.cpp',
	'src/CImageLoaderBMP.cpp',
	'src/CImageLoaderDDS.cpp',
	'src/CImageLoaderJPG.cpp',
	'src/CImageLoaderPCX.cpp',
	'src/CImageLoaderPNG.cpp',
	'src/CImageLoaderPPM.cpp',
	'src/CImageLoaderPSD.cpp',
	'src/CImageLoaderPVR.cpp',
	'src/CImageLoaderRGB.cpp',
	'src/CImageLoaderTGA.cpp',
	'src/CImageLoaderWAL.cpp',
	'src/CImageWriterBMP.cpp',
	'src/CImageWriterJPG.cpp',
	'src/CImageWriterPCX.cpp',
	'src/CImageWriterPNG.cpp',
	'src/CImageWriterPPM.cpp',
	'src/CImageWriterPSD.cpp',
	'src/CImageWriterTGA.cpp',
	'src/CIrrDeviceConsole.cpp',
	'src/CIrrDeviceFB.cpp',
	'src/CIrrDeviceLinux.cpp',
	'src/CIrrDeviceSDL.cpp',
	'src/CIrrDeviceSDL2.cpp',
	'src/CIrrDeviceSDL3.cpp',
	'src/CIrrDeviceStub.cpp',
	'src/CIrrDeviceWayland.cpp',
	'src/CIrrDeviceWin32.cpp',
	'src/CIrrDeviceWin32WindowsVersionWMI.cpp',
	'src/CIrrMeshFileLoader.cpp',
	'src/CIrrMeshWriter.cpp',
	'src/CLMTSMeshFileLoader.cpp',
	'src/CLWOMeshFileLoader.cpp',
	'src/CLightSceneNode.cpp',
	'src/CLimitReadFile.cpp',
	'src/CLogger.cpp',
	'src/CMD2MeshFileLoader.cpp',
	'src/CMD3MeshFileLoader.cpp',
	'src/CMS3DMeshFileLoader.cpp',
	'src/CMY3DMeshFileLoader.cpp',
	'src/CMemoryFile.cpp',
	'src/CMeshCache.cpp',
	'src/CMeshManipulator.cpp',
	'src/CMeshSceneNode.cpp',
	'src/CMeshTextureLoader.cpp',
	'src/CMetaTriangleSelector.cpp',
	'src/CMountPointReader.cpp',
	'src/CNPKReader.cpp',
	'src/CNullDriver.cpp',
	'src/COBJMeshFileLoader.cpp',
	'src/COBJMeshWriter.cpp',
	'src/COCTLoader.cpp',
	'src/COGLES2BaseFunctionsHandler.cpp',
	'src/COGLES2Driver.cpp',
	'src/COGLES2ExtensionHandler.cpp',
	'src/COGLES2FixedPipelineRenderer.cpp',
	'src/COGLES2MaterialRenderer.cpp',
	'src/COGLES2NormalMapRenderer.cpp',
	'src/COGLES2ParallaxMapRenderer.cpp',
	'src/COGLES2Renderer2D.cpp',
	'src/COGLES2StaticShaders.cpp',
	'src/COGLESBaseFunctionsHandler.cpp',
	'src/COGLESDriver.cpp',
	'src/COGLESExtensionHandler.cpp',
	'src/COctreeSceneNode.cpp',
	'src/COctreeTriangleSelector.cpp',
	'src/COgreMeshFileLoader.cpp',
	'src/COpenGLBaseFunctionsHandler.cpp',
	'src/COpenGLCacheHandler.cpp',
	'src/COpenGLDriver.cpp',
	'src/COpenGLExtensionHandler.cpp',
	'src/COpenGLNormalMapRenderer.cpp',
	'src/COpenGLParallaxMapRenderer.cpp',
	'src/COpenGLSLMaterialRenderer.cpp',
	'src/COpenGLShaderMaterialRenderer.cpp',
	'src/CPLYMeshFileLoader.cpp',
	'src/CPLYMeshWriter.cpp',
	'src/CPakReader.cpp',
	'src/CParticleAnimatedMeshSceneNodeEmitter.cpp',
	'src/CParticleAttractionAffector.cpp',
	'src/CParticleBoxEmitter.cpp',
	'src/CParticleCylinderEmitter.cpp',
	'src/CParticleFadeOutAffector.cpp',
	'src/CParticleGravityAffector.cpp',
	'src/CParticleMeshEmitter.cpp',
	'src/CParticlePointEmitter.cpp',
	'src/CParticleRingEmitter.cpp',
	'src/CParticleRotationAffector.cpp',
	'src/CParticleScaleAffector.cpp',
	'src/CParticleSphereEmitter.cpp',
	'src/CParticleSystemSceneNode.cpp',
	'src/CProfiler.cpp',
	'src/CQ3LevelMesh.cpp',
	'src/CQuake3ShaderSceneNode.cpp',
	'src/CReadFile.cpp',
	'src/CSDL2ContextManager.cpp',
	'src/CSDL3ContextManager.cpp',
	'src/CSDLContextManager.cpp',
	'src/CSMFMeshFileLoader.cpp',
	'src/CSTLMeshFileLoader.cpp',
	'src/CSTLMeshWriter.cpp',
	'src/CSceneCollisionManager.cpp',
	'src/CSceneLoaderIrr.cpp',
	'src/CSceneManager.cpp',
	'src/CSceneNodeAnimatorCameraFPS.cpp',
	'src/CSceneNodeAnimatorCameraMaya.cpp',
	'src/CSceneNodeAnimatorCollisionResponse.cpp',
	'src/CSceneNodeAnimatorDelete.cpp',
	'src/CSceneNodeAnimatorFlyCircle.cpp',
	'src/CSceneNodeAnimatorFlyStraight.cpp',
	'src/CSceneNodeAnimatorFollowSpline.cpp',
	'src/CSceneNodeAnimatorRotation.cpp',
	'src/CSceneNodeAnimatorTexture.cpp',
	'src/CShadowVolumeSceneNode.cpp',
	'src/CSkinnedMesh.cpp',
	'src/CSkyBoxSceneNode.cpp',
	'src/CSkyDomeSceneNode.cpp',
	'src/CSoftwareDriver.cpp',
	'src/CSoftwareDriver2.cpp',
	'src/CSoftwareTexture.cpp',
	'src/CSoftwareTexture2.cpp',
	'src/CSphereSceneNode.cpp',
	'src/CTRFlat.cpp',
	'src/CTRFlatWire.cpp',
	'src/CTRGouraud.cpp',
	'src/CTRGouraud2.cpp',
	'src/CTRGouraudAlpha2.cpp',
	'src/CTRGouraudAlphaNoZ2.cpp',
	'src/CTRGouraudNoZ2.cpp',
	'src/CTRGouraudWire.cpp',
	'src/CTRNormalMap.cpp',
	'src/CTRStencilShadow.cpp',
	'src/CTRTextureBlend.cpp',
	'src/CTRTextureDetailMap2.cpp',
	'src/CTRTextureFlat.cpp',
	'src/CTRTextureFlatWire.cpp',
	'src/CTRTextureGouraud.cpp',
	'src/CTRTextureGouraud2.cpp',
	'src/CTRTextureGouraudAdd.cpp',
	'src/CTRTextureGouraudAdd2.cpp',
	'src/CTRTextureGouraudAddNoZ2.cpp',
	'src/CTRTextureGouraudAlpha.cpp',
	'src/CTRTextureGouraudAlphaNoZ.cpp',
	'src/CTRTextureGouraudNoZ.cpp',
	'src/CTRTextureGouraudNoZ2.cpp',
	'src/CTRTextureGouraudVertexAlpha2.cpp',
	'src/CTRTextureGouraudWire.cpp',
	'src/CTRTextureLightMap2_Add.cpp',
	'src/CTRTextureLightMap2_M1.cpp',
	'src/CTRTextureLightMap2_M2.cpp',
	'src/CTRTextureLightMap2_M4.cpp',
	'src/CTRTextureLightMapGouraud2_M4.cpp',
	'src/CTRTextureWire2.cpp',
	'src/CTR_transparent_reflection_2_layer.cpp',
	'src/CTarReader.cpp',
	'src/CTerrainSceneNode.cpp',
	'src/CTerrainTriangleSelector.cpp',
	'src/CTextSceneNode.cpp',
	'src/CTriangleBBSelector.cpp',
	'src/CTriangleSelector.cpp',
	'src/CVideoModeList.cpp',
	'src/CVolumeLightSceneNode.cpp',
	'src/CWADReader.cpp',
	'src/CWGLManager.cpp',
	'src/CWaterSurfaceSceneNode.cpp',
	'src/CWebGL1Driver.cpp',
	'src/CWin32DropTarget.cpp',
	'src/CWriteFile.cpp',
	'src/CXMLReader.cpp',
	'src/CXMLWriter.cpp',
	'src/CXMeshFileLoader.cpp',
	'src/CZBuffer.cpp',
	'src/CZipReader.cpp',
	'src/DbusLoader.cpp',
	'src/IBurningShader.cpp',
	'src/LibX11Loader.cpp',
	'src/LibdecorLoader.cpp',
	'src/burning_shader_color.cpp',
	'src/cursor_shape_v1_protocol.cpp',
	'src/irrXML.cpp',
	'src/leakHunter.cpp',
	'src/org_kde_kwin_server_decoration_manager_client_protocol.cpp',
	'src/os.cpp',
	'src/utf8.cpp',
	'src/xdg_decoration_unstable_v1_protocol.c',
	'src/xdg_shell_protocol.cpp',
	'src/ztext_input_unstable_v3_client_protocol.cpp',
	'src/zxdg_shell_unstable_v6_client_protocol.cpp',
]

irrlicht_defines = [
	'-D_IRR_STATIC_LIB_',
	'-DIRRLICHT_FAST_MATH',
	'-DNO_IRR_COMPILE_WITH_CONSOLE_DEVICE_',
	'-DNO_IRR_COMPILE_WITH_DIRECT3D_8_',
	'-DNO_IRR_COMPILE_WITH_DIRECTINPUT_JOYSTICK_',
	'-DNO_IRR_COMPILE_WITH_JOYSTICK_EVENTS_',
	'-DNO_IRR_COMPILE_WITH_SOFTWARE_',
	'-DNO_IRR_COMPILE_WITH_BURNINGSVIDEO_',
	'-DNO_IRR_COMPILE_WITH_IRR_SCENE_LOADER_',
	'-DNO_IRR_COMPILE_WITH_SKINNED_MESH_SUPPORT_',
	'-DNO_IRR_COMPILE_WITH_IRR_MESH_LOADER_',
	'-DNO_IRR_COMPILE_WITH_HALFLIFE_LOADER_',
	'-DNO_IRR_COMPILE_WITH_MD2_LOADER_',
	'-DNO_IRR_COMPILE_WITH_MD3_LOADER_',
	'-DNO_IRR_COMPILE_WITH_3DS_LOADER_',
	'-DNO_IRR_COMPILE_WITH_COLLADA_LOADER_',
	'-DNO_IRR_COMPILE_WITH_CSM_LOADER_',
	'-DNO_IRR_COMPILE_WITH_BSP_LOADER_',
	'-DNO_IRR_COMPILE_WITH_DMF_LOADER_',
	'-DNO_IRR_COMPILE_WITH_LMTS_LOADER_',
	'-DNO_IRR_COMPILE_WITH_MY3D_LOADER_',
	'-DNO_IRR_COMPILE_WITH_OBJ_LOADER_',
	'-DNO_IRR_COMPILE_WITH_OCT_LOADER_',
	'-DNO_IRR_COMPILE_WITH_LWO_LOADER_',
	'-DNO_IRR_COMPILE_WITH_STL_LOADER_',
	'-DNO_IRR_COMPILE_WITH_PLY_LOADER_',
	'-DNO_IRR_COMPILE_WITH_SMF_LOADER_',
	'-DNO_IRR_COMPILE_WITH_IRR_WRITER_',
	'-DNO_IRR_COMPILE_WITH_COLLADA_WRITER_',
	'-DNO_IRR_COMPILE_WITH_STL_WRITER_',
	'-DNO_IRR_COMPILE_WITH_OBJ_WRITER_',
	'-DNO_IRR_COMPILE_WITH_PLY_WRITER_',
	'-DNO_IRR_COMPILE_WITH_PCX_LOADER_',
	'-DNO_IRR_COMPILE_WITH_PPM_LOADER_',
	'-DNO_IRR_COMPILE_WITH_PSD_LOADER_',
	'-DNO_IRR_COMPILE_WITH_TGA_LOADER_',
	'-DNO_IRR_COMPILE_WITH_WAL_LOADER_',
	'-DNO_IRR_COMPILE_WITH_LMP_LOADER_',
	'-DNO_IRR_COMPILE_WITH_RGB_LOADER_',
	'-DNO_IRR_COMPILE_WITH_PCX_WRITER_',
	'-DNO_IRR_COMPILE_WITH_PPM_WRITER_',
	'-DNO_IRR_COMPILE_WITH_PSD_WRITER_',
	'-DNO_IRR_COMPILE_WITH_TGA_WRITER_',
	'-DNO__IRR_COMPILE_WITH_PAK_ARCHIVE_LOADER_',
	'-DNO__IRR_COMPILE_WITH_NPK_ARCHIVE_LOADER_',
	'-DNO__IRR_COMPILE_WITH_WAD_ARCHIVE_LOADER_',
	'-DNO_IRR_USE_NON_SYSTEM_ZLIB_',
	'-DNO_IRR_USE_NON_SYSTEM_BZLIB_',
	'-DNO_IRR_USE_NON_SYSTEM_LIB_PNG_',
	'-DNO_IRR_USE_NON_SYSTEM_JPEG_LIB_',
]

irrlicht_deps = [
	dependency('zlib'),
	dependency('bzip2'),
	dependency('libpng'),
	dependency('libjpeg'),
]

if host_machine.system() == 'darwin'
	add_languages('objcpp', native: false)
	cat = find_program('cat')
	to_objc = generator(cat,
            output  : '@BASENAME@.mm',
            arguments : ['@INPUT@'],
			capture : true)
	irrlicht_sources += to_objc.process([
		'src/COSOperator.cpp',
		'src/Irrlicht.cpp',
	])
	irrlicht_sources += [
		'src/CIrrDeviceOSX.mm',
		'src/CNSOGLManager.mm',
	]
else
	irrlicht_sources += [
		'src/COSOperator.cpp',
		'src/Irrlicht.cpp',
	]
endif

if host_machine.system() == 'windows'
	irrlicht_defines += [
		'-D_IRR_COMPILE_WITH_OGLES1_',
		'-DIRR_COMPILE_WITH_DX9_DEV_PACK',
	]
	cpp = meson.get_compiler('cpp')
	irrlicht_deps += dependency('gl')
	irrlicht_deps += cpp.find_library('imm32')
	irrlicht_deps += cpp.find_library('wbemuuid')
elif host_machine.system() == 'darwin'
	irrlicht_deps += dependency('gl')
	irrlicht_deps += dependency('appleframeworks', modules: 'Foundation')
	irrlicht_deps += dependency('appleframeworks', modules: 'AppKit')
endif

irrlicht_lib = static_library(
	'irrlicht',
	cpp_args : irrlicht_defines,
	c_args : irrlicht_defines,
	objcpp_args : irrlicht_defines,
	objc_args : irrlicht_defines,
	include_directories: irrlicht_inc + include_directories('./src'),
	sources: irrlicht_sources,
    dependencies: irrlicht_deps,
	override_options: ['warning_level=0'],
)

irrlicht_dep = declare_dependency(link_with : irrlicht_lib, include_directories : irrlicht_inc)
